# permissions for end users to view deploymentlabelchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deploymentlabelcheck-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8builder-demo
    app.kubernetes.io/part-of: k8builder-demo
    app.kubernetes.io/managed-by: kustomize
  name: deploymentlabelcheck-viewer-role
rules:
- apiGroups:
  - demo.demo.jonlimpw.io
  resources:
  - deploymentlabelchecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.demo.jonlimpw.io
  resources:
  - deploymentlabelchecks/status
  verbs:
  - get
