---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - demo.demo.jonlimpw.io
  resources:
  - deploymentlabelchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.demo.jonlimpw.io
  resources:
  - deploymentlabelchecks/finalizers
  verbs:
  - update
- apiGroups:
  - demo.demo.jonlimpw.io
  resources:
  - deploymentlabelchecks/status
  verbs:
  - get
  - patch
  - update
