apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tags.datadoghq.com/env: kubebuilder
    tags.datadoghq.com/service: adservice_nolabel
    tags.datadoghq.com/version: 1.0.0
  name: adservice-nolabel
  namespace: kubebuilder
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: adservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: adservice
        tags.datadoghq.com/env: kubebuilder
        tags.datadoghq.com/service: adservice_nolabel
        tags.datadoghq.com/version: 1.0.0
      annotations:
        admission.datadoghq.com/python-lib.version: v2.6.5	
    spec:
      containers:
      - env:
        - name: PORT
          value: "9555"
        - name: DD_LOGS_INJECTION
          value: "true"
        image: jonlimpw/notes-java-app:latest
        imagePullPolicy: IfNotPresent
        name: server
        ports:
        - containerPort: 9555
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 200m
            memory: 180Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: default